config/routes.rb
Rails.application.routes.draw do
	root to: redirect('/voices#index')
  	resources :voices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/voice.rb
class Voice < ApplicationRecord
	mount_uploader :source_url, RecordingUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/voices_controller.rb
class VoicesController < ApplicationController
  before_action :set_voice, only: [:show, :edit, :update, :destroy]

  # GET /voices
  # GET /voices.json
  def index
    @voices = Voice.all
    #ConvertVoicesJob.perform_later
    #UserMailer.converted_email(Voice.last).deliver
  end

  # GET /voices/1
  # GET /voices/1.json
  def show
  end

  # GET /voices/new
  def new
    @voice = Voice.new
  end

  # GET /voices/1/edit
  def edit
  end

  # POST /voices
  # POST /voices.json
  def create
    @voice = Voice.new(voice_params)

    respond_to do |format|
      if @voice.save
        format.html { redirect_to @voice, notice: 'Voice was successfully created.' }
        format.json { render :show, status: :created, location: @voice }
      else
        format.html { render :new }
        format.json { render json: @voice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voices/1
  # PATCH/PUT /voices/1.json
  def update
    respond_to do |format|
      if @voice.update(voice_params)
        format.html { redirect_to @voice, notice: 'Voice was successfully updated.' }
        format.json { render :show, status: :ok, location: @voice }
      else
        format.html { render :edit }
        format.json { render json: @voice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voices/1
  # DELETE /voices/1.json
  def destroy
    @voice.destroy
    respond_to do |format|
      format.html { redirect_to voices_url, notice: 'Voice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voice
      @voice = Voice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voice_params
      params.require(:voice).permit(:creation, :email, :name, :last, :converted, :message, :source_url, :destination_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/voices_helper.rb
module VoicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoicesConverter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/voices/_form.html.erb
<%= form_for(voice) do |f| %>
  <% if voice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voice.errors.count, "error") %> prohibited this voice from being saved:</h2>

      <ul>
      <% voice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :creation %>
    <%= f.date_select :creation %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :last %>
    <%= f.text_field :last %>
  </div>

  <div class="field">
    <%= f.label :converted %>
    <%= f.check_box :converted %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_field :message %>
  </div>

  <div class="field">
    <%= f.label :source_url %>
    <%= f.file_field :source_url %>
  </div>

  <div class="field">
    <%= f.label :destination_url %>
    <%= f.text_field :destination_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voices/edit.html.erb
<h1>Editing Voice</h1>

<%= render 'form', voice: @voice %>

<%= link_to 'Show', @voice %> |
<%= link_to 'Back', voices_path %>

app/views/voices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Voices</h1>

<table>
  <thead>
    <tr>
      <th>Creation</th>
      <th>Email</th>
      <th>Name</th>
      <th>Last</th>
      <th>Converted</th>
      <th>Message</th>
      <th>Source url</th>
      <th>Destination url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voices.each do |voice| %>
      <tr>
        <td><%= voice.creation %></td>
        <td><%= voice.email %></td>
        <td><%= voice.name %></td>
        <td><%= voice.last %></td>
        <td><%= voice.converted %></td>
        <td><%= voice.message %></td>
        <td><%= voice.source_url %></td>
        <td><%= voice.destination_url %></td>
        <td><%= link_to 'Show', voice %></td>
        <td><%= link_to 'Edit', edit_voice_path(voice) %></td>
        <td><%= link_to 'Destroy', voice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voice', new_voice_path %>

app/views/voices/new.html.erb
<h1>New Voice</h1>

<%= render 'form', voice: @voice %>

<%= link_to 'Back', voices_path %>

app/views/voices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Creation:</strong>
  <%= @voice.creation %>
</p>

<p>
  <strong>Email:</strong>
  <%= @voice.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @voice.name %>
</p>

<p>
  <strong>Last:</strong>
  <%= @voice.last %>
</p>

<p>
  <strong>Converted:</strong>
  <%= @voice.converted %>
</p>

<p>
  <strong>Message:</strong>
  <%= @voice.message %>
</p>

<p>
  <strong>Source url:</strong>
  <%= @voice.source_url %>
</p>

<p>
  <strong>Destination url:</strong>
  <%= @voice.destination_url %>
</p>

<%= link_to 'Edit', edit_voice_path(@voice) %> |
<%= link_to 'Back', voices_path %>